services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  app:
    container_name: auth_microservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: auth_db
      DB_HOST: db
      DB_PORT: 5432
      SSL_MODE: disable
    depends_on:
      - db

volumes:
  postgres_data: